services:
  runtime:
    build:
      context: .
      dockerfile: ./docker/runtime/Dockerfile
    command: sleep infinity
    container_name: runtime
    tty: true
    working_dir: /app
    volumes:
      - ./data.sqlite3:/app/data.sqlite3
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
